# Generated by Django 5.2.3 on 2025-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=200,
                        verbose_name='Título do Conjunto de Dados',
                    ),
                ),
                (
                    'unidade',
                    models.CharField(
                        help_text='A qual unidade/setor estes dados pertencem.',
                        max_length=100,
                        verbose_name='Unidade Correspondente',
                    ),
                ),
                (
                    'csv_file',
                    models.FileField(
                        upload_to='dashboards/csvs/',
                        verbose_name='Arquivo CSV',
                    ),
                ),
                (
                    'uploaded_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Data de Upload'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dado para Dashboard',
                'verbose_name_plural': 'Dados para Dashboards',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
            },
        ),
    ]
