# Generated by Django 5.2.3 on 2025-06-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título.', max_length=220, unique=True)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('post_type', models.CharField(choices=[('NEWS', 'Notícia'), ('ARTICLE', 'Artigo'), ('INSTRUCTION', 'Instrução')], default='ARTICLE', max_length=20, verbose_name='Tipo de Postagem')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/images/', verbose_name='Imagem de Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
