# Generated by Django 5.2.3 on 2025-06-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardData',
        ),
        migrations.AlterField(
            model_name='profile',
            name='unidade',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ASSCOM', 'ASSCOM'),
                    ('DAFI', 'DAFI'),
                    ('DIRC', 'DIRC'),
                    ('DTIC', 'DTIC'),
                    ('GABD', 'GABD'),
                    ('GACD', 'GACD'),
                    ('GADP', 'GADP'),
                    ('GAOI', 'GAOI'),
                    ('GAQS', 'GAQS'),
                    ('GASI', 'GASI'),
                    ('GCCP', 'GCCP'),
                    ('GCES', 'GCES'),
                    ('GCOT', 'GCOT'),
                    ('GCTO', 'GCTO'),
                    ('GEDC', 'GEDC'),
                    ('GEFI', 'GEFI'),
                    ('GEGD', 'GEGD'),
                    ('GEOR', 'GEOR'),
                    ('GEPM', 'GEPM'),
                    ('GEPP', 'GEPP'),
                    ('GGES', 'GGES'),
                    ('GETS', 'GETS'),
                    ('GFAC', 'GFAC'),
                    ('GFTG', 'GFTG'),
                    ('GICF', 'GICF'),
                    ('GIAP', 'GIAP'),
                    ('GPAC', 'GPAC'),
                    ('GPGD', 'GPGD'),
                    ('GPIN', 'GPIN'),
                    ('GPMM', 'GPMM'),
                    ('GPSE', 'GPSE'),
                    ('GSPT', 'GSPT'),
                    ('GRCO', 'GRCO'),
                    ('GSIC', 'GSIC'),
                    ('GSUP', 'GSUP'),
                    ('OUVIDORIA', 'OUVIDORIA'),
                    ('UGADM', 'UGADM'),
                    ('UGACO', 'UGACO'),
                    ('UGARQ', 'UGARQ'),
                    ('UGCOF', 'UGCOF'),
                    ('UGGDC', 'UGGDC'),
                    ('UGGDI', 'UGGDI'),
                    ('UGGOV', 'UGGOV'),
                    ('UGITI', 'UGITI'),
                    ('UGPES', 'UGPES'),
                    ('UGPRO', 'UGPRO'),
                    ('UGSDG', 'UGSDG'),
                    ('UGSTI', 'UGSTI'),
                    ('UGVEN', 'UGVEN'),
                    ('UGEPV', 'UGEPV'),
                    ('UGENP', 'UGENP'),
                    ('UNICRS', 'UNICRS'),
                    ('UNIJUR', 'UNIJUR'),
                    ('UNISECI', 'UNISECI'),
                    ('OUTRO', 'Outro / Não especificado'),
                ],
                max_length=10,
                null=True,
                verbose_name='Unidade/Setor',
            ),
        ),
    ]
